name: Deploy to Server

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create the private key file from GitHub secrets
      - name: Create private key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      # Step 3: Test SSH connection directly (without ssh-agent)
      - name: Test SSH Connection
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no -v hadis@116.203.213.63 "echo SSH connected"

      # Step 4: Deploy to the server
      - name: Deploy to Server
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no hadis@116.203.213.63 << 'EOF'
          cd example-app
          git pull origin main
          sudo apt-get update
          sudo apt-get install -y php-intl
          rm -rf vendor/
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:cache
          EOF

