name: Deploy to Server

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on every push to any branch
    # Optionally, you can trigger it on all tags as well:
    # tags:
    #   - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Add SSH Key to Agent
    - name: Add SSH Key to Agent
      run: |
        # Write the SSH private key to a file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        # Start the SSH agent
        eval $(ssh-agent -s)
        # Add the private key to the agent
        ssh-add private_key

    # Step 3: Deploy to the server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no hadis@116.203.213.63 << 'EOF'
        cd example-app
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan cache:clear
        php artisan config:clear
        php artisan route:cache
        EOF



