name: Deploy to Server

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Add SSH Key to Agent
    - name: Add SSH Key to Agent
      run: |
        # Write the SSH private key to a file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        # Start the SSH agent
        eval $(ssh-agent -s)
        # Add the private key to the agent
        ssh-add private_key

    # Step 3: Test SSH connection (Optional, for debugging)
    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no hadis@116.203.213.63 "echo SSH connected"

    # Step 4: Deploy to the server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no hadis@116.203.213.63 << 'EOF'
        cd example-app
        # Checkout public/index.php to ensure it's not changed
        git checkout -- public/index.php
        # Reset the repository to discard any local changes
        git reset --hard
        # Pull the latest changes from the main branch
        git pull origin main
        # Run deployment commands
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan cache:clear
        php artisan config:clear
        php artisan route:cache
        EOF
