name: Deploy to Server

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to the server
      - name: Deploy to Server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          # Deploy using SSH directly without ssh-agent
          ssh -i private_key -o StrictHostKeyChecking=no hadis@116.203.213.63 << 'EOF'
          cd example-app
          git pull origin main
          # Install PHP extensions and dependencies
          sudo apt-get update
          sudo apt-get install -y php-intl
          rm -rf vendor/
          composer install --no-dev --optimize-autoloader
          # Build frontend assets
          npm install
          npm run build
          # Run Laravel deployment commands
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:cache
          EOF


