name: Deploy to Server

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Add SSH Key to Agent
    - name: Add SSH Key to Agent
      run: |
        # Write the SSH private key to a file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        # Start the SSH agent
        eval "$(ssh-agent -s)"
        # Add the private key to the agent
        ssh-add private_key

    # Step 3: Add Server to Known Hosts
    - name: Add Server to Known Hosts
      run: |
        # Add the server's SSH host key to avoid strict host key checking issues
        mkdir -p ~/.ssh
        ssh-keyscan -H 116.203.213.63 >> ~/.ssh/known_hosts

    # Step 4: Test SSH connection (Optional, for debugging)
    - name: Test SSH Connection
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no hadis@116.203.213.63 "echo SSH connected"

    # Step 5: Deploy to the server
    - name: Deploy to Server
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no hadis@116.203.213.63 << 'EOF'
        cd example-app
        # Ensure the repository is in a clean state
        git checkout -- public/index.php
        git reset --hard
        # Pull the latest changes from the main branch
        git pull origin main
        # Run deployment commands
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan cache:clear
        php artisan config:clear
        php artisan route:cache
        EOF

