name: Deploy to Server

on:
  push:
    branches:
      - main # Replace this with your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy to the server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no hadis@116.203.213.63 << 'EOF'
        cd example-app
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan cache:clear
        php artisan config:clear
        php artisan route:cache
        EOF

